services:
  svelte:
    build: .
    ports:
      - "5173:5173"
    volumes:
      - .:/app  
    
  whisper:
    build: 
      context: whisper
    ports:
      - 5174:5000
    volumes:
      - .:/app
    tty: true

# volumes:
  # node_modules: